chain_config: ./configs/genesis.json
secrets_config: ""
data_dir: "./data/node-2"
block_gas_target: "0x0"
grpc_addr: ":30000"
jsonrpc_addr: ":30002"
telemetry:
    prometheus_addr: ""
network:
    no_discover: false
    libp2p_addr: :30001
    nat_addr: ""
    dns_addr: ""
    max_peers: -1
    max_outbound_peers: -1
    max_inbound_peers: -1
seal: true
tx_pool:
    price_limit: 0
    max_slots: 4096
log_level: DEBUG
restore_file: ""
block_time_s: 2
ibft_base_time_s: 10
headers:
    access_control_allow_origins:
        - '*'
log_to: ""
